working_directory = "/home/antoine/"

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 12.0

[font.bold]
family = "Roboto Mono for Powerline"
style = "Bold"

[font.bold_italic]
family = "Roboto Mono for Powerline"
style = "Bold Italic"

[font.italic]
family = "Roboto Mono Medium for Powerline"
style = "Italic"

[font.normal]
family = "Roboto Mono Medium for Powerline"
style = "Regular"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[shell]
program = "/usr/bin/tmux"

[window]
decorations = "none"
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0
