general.working_directory = "/home/antoine/"

[cursor]
style = "Block"

[font]
size = 14.0

[font.bold]
family = "IosevkaTerm NF"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm NF"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm NF"
style = "Italic"

[font.normal]
family = "IosevkaTerm NF"
style = "Regular"

[font.offset]
x = 1
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/usr/bin/tmux"

[window]
decorations = "full"
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0
